/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril;

import com.anduril.core.ClientOptions;
import com.anduril.core.Environment;
import com.anduril.core.OAuthTokenSupplier;
import com.anduril.resources.oauth2.OAuth2Client;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import okhttp3.OkHttpClient;

public class LatticeBuilder {
    private Optional<Integer> timeout = Optional.empty();

    private Optional<Integer> maxRetries = Optional.empty();

    private final Map<String, String> customHeaders = new HashMap<>();

    protected Environment environment = Environment.DEFAULT;

    private OkHttpClient httpClient;

    /**
     * Creates a builder that uses a pre-generated access token for authentication.
     * Use this when you already have a valid access token and want to bypass
     * the OAuth client credentials flow.
     *
     * @param token The access token to use for Authorization header
     * @return A builder configured for token authentication
     */
    public static _TokenAuth withToken(String token) {
        return new _TokenAuth(token);
    }

    /**
     * Creates a builder that uses OAuth client credentials for authentication.
     * The builder will automatically handle token acquisition and refresh.
     *
     * @param clientId The OAuth client ID
     * @param clientSecret The OAuth client secret
     * @return A builder configured for OAuth client credentials authentication
     */
    public static _CredentialsAuth withCredentials(String clientId, String clientSecret) {
        return new _CredentialsAuth(clientId, clientSecret);
    }

    public LatticeBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public LatticeBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    public LatticeBuilder timeout(int timeout) {
        this.timeout = Optional.of(timeout);
        return this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    public LatticeBuilder maxRetries(int maxRetries) {
        this.maxRetries = Optional.of(maxRetries);
        return this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    public LatticeBuilder httpClient(OkHttpClient httpClient) {
        this.httpClient = httpClient;
        return this;
    }

    /**
     * Add a custom header to be sent with all requests.
     * For headers that need to be computed dynamically or conditionally, use the setAdditional() method override instead.
     *
     * @param name The header name
     * @param value The header value
     * @return This builder for method chaining
     */
    public LatticeBuilder addHeader(String name, String value) {
        this.customHeaders.put(name, value);
        return this;
    }

    protected ClientOptions buildClientOptions() {
        ClientOptions.Builder builder = ClientOptions.builder();
        setEnvironment(builder);
        setAuthentication(builder);
        setHttpClient(builder);
        setTimeouts(builder);
        setRetries(builder);
        for (Map.Entry<String, String> header : this.customHeaders.entrySet()) {
            builder.addHeader(header.getKey(), header.getValue());
        }
        setAdditional(builder);
        return builder.build();
    }

    /**
     * Sets the environment configuration for the client.
     * Override this method to modify URLs or add environment-specific logic.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setEnvironment(ClientOptions.Builder builder) {
        builder.environment(this.environment);
    }

    /**
     * Override this method to customize authentication.
     * This method is called during client options construction to set up authentication headers.
     *
     * @param builder The ClientOptions.Builder to configure
     *
     * Example:
     * <pre>{@code
     * &#64;Override
     * protected void setAuthentication(ClientOptions.Builder builder) {
     *     super.setAuthentication(builder); // Keep existing auth
     *     builder.addHeader("X-API-Key", this.apiKey);
     * }
     * }</pre>
     */
    protected void setAuthentication(ClientOptions.Builder builder) {}

    /**
     * Sets the request timeout configuration.
     * Override this method to customize timeout behavior.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setTimeouts(ClientOptions.Builder builder) {
        if (this.timeout.isPresent()) {
            builder.timeout(this.timeout.get());
        }
    }

    /**
     * Sets the retry configuration for failed requests.
     * Override this method to implement custom retry strategies.
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setRetries(ClientOptions.Builder builder) {
        if (this.maxRetries.isPresent()) {
            builder.maxRetries(this.maxRetries.get());
        }
    }

    /**
     * Sets the OkHttp client configuration.
     * Override this method to customize HTTP client behavior (interceptors, connection pools, etc).
     *
     * @param builder The ClientOptions.Builder to configure
     */
    protected void setHttpClient(ClientOptions.Builder builder) {
        if (this.httpClient != null) {
            builder.httpClient(this.httpClient);
        }
    }

    /**
     * Override this method to add any additional configuration to the client.
     * This method is called at the end of the configuration chain, allowing you to add
     * custom headers, modify settings, or perform any other client customization.
     *
     * @param builder The ClientOptions.Builder to configure
     *
     * Example:
     * <pre>{@code
     * &#64;Override
     * protected void setAdditional(ClientOptions.Builder builder) {
     *     builder.addHeader("X-Request-ID", () -&gt; UUID.randomUUID().toString());
     *     builder.addHeader("X-Client-Version", "1.0.0");
     * }
     * }</pre>
     */
    protected void setAdditional(ClientOptions.Builder builder) {}

    /**
     * Override this method to add custom validation logic before the client is built.
     * This method is called at the beginning of the build() method to ensure the configuration is valid.
     * Throw an exception to prevent client creation if validation fails.
     *
     * Example:
     * <pre>{@code
     * &#64;Override
     * protected void validateConfiguration() {
     *     super.validateConfiguration(); // Run parent validations
     *     if (tenantId == null || tenantId.isEmpty()) {
     *         throw new IllegalStateException("tenantId is required");
     *     }
     * }
     * }</pre>
     */
    protected void validateConfiguration() {}

    public Lattice build() {
        validateConfiguration();
        return new Lattice(buildClientOptions());
    }

    public static final class _TokenAuth extends LatticeBuilder {
        private final String token;

        _TokenAuth(String token) {
            this.token = token;
        }

        @Override
        protected void setAuthentication(ClientOptions.Builder builder) {
            builder.addHeader("Authorization", "Bearer " + this.token);
        }
    }

    public static final class _CredentialsAuth extends LatticeBuilder {
        private final String clientId;

        private final String clientSecret;

        private String code = null;

        private String redirectUri = null;

        private String refreshToken = null;

        private String username = null;

        private String password = null;

        private String scope = null;

        _CredentialsAuth(String clientId, String clientSecret) {
            this.clientId = clientId;
            this.clientSecret = clientSecret;
        }

        public _CredentialsAuth code(String code) {
            this.code = code;
            return this;
        }

        public _CredentialsAuth redirectUri(String redirectUri) {
            this.redirectUri = redirectUri;
            return this;
        }

        public _CredentialsAuth refreshToken(String refreshToken) {
            this.refreshToken = refreshToken;
            return this;
        }

        public _CredentialsAuth username(String username) {
            this.username = username;
            return this;
        }

        public _CredentialsAuth password(String password) {
            this.password = password;
            return this;
        }

        public _CredentialsAuth scope(String scope) {
            this.scope = scope;
            return this;
        }

        @Override
        public Lattice build() {
            validateConfiguration();
            ClientOptions baseOptions = buildClientOptions();
            OAuth2Client authClient = new OAuth2Client(baseOptions);
            OAuthTokenSupplier oAuthTokenSupplier = new OAuthTokenSupplier(
                    this.clientId,
                    this.clientSecret,
                    this.code,
                    this.redirectUri,
                    this.refreshToken,
                    this.username,
                    this.password,
                    this.scope,
                    authClient);
            ClientOptions finalOptions = ClientOptions.Builder.from(baseOptions)
                    .addHeader("Authorization", oAuthTokenSupplier)
                    .build();
            return new Lattice(finalOptions);
        }
    }
}
