/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.resources.entities;

import com.anduril.core.ClientOptions;
import com.anduril.core.LatticeApiException;
import com.anduril.core.LatticeException;
import com.anduril.core.LatticeHttpResponse;
import com.anduril.core.MediaTypes;
import com.anduril.core.ObjectMappers;
import com.anduril.core.RequestOptions;
import com.anduril.core.ResponseBodyReader;
import com.anduril.core.Stream;
import com.anduril.errors.BadRequestError;
import com.anduril.errors.NotFoundError;
import com.anduril.errors.RequestTimeoutError;
import com.anduril.errors.TooManyRequestsError;
import com.anduril.errors.UnauthorizedError;
import com.anduril.resources.entities.requests.EntityEventRequest;
import com.anduril.resources.entities.requests.EntityOverride;
import com.anduril.resources.entities.requests.EntityStreamRequest;
import com.anduril.resources.entities.requests.GetEntityRequest;
import com.anduril.resources.entities.requests.RemoveEntityOverrideRequest;
import com.anduril.resources.entities.types.StreamEntitiesResponse;
import com.anduril.resources.entity.types.Error;
import com.anduril.types.Entity;
import com.anduril.types.EntityEventResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEntitiesClient {
    protected final ClientOptions clientOptions;

    public RawEntitiesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Publish an entity for ingest into the Entities API. Entities created with this method are &quot;owned&quot; by the originator: other sources,
     * such as the UI, may not edit or delete these entities. The server validates entities at API call time and
     * returns an error if the entity is invalid.
     * <p>An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
     * then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
     * provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.</p>
     */
    public LatticeHttpResponse<Entity> publishEntity() {
        return publishEntity(Entity.builder().build());
    }

    /**
     * Publish an entity for ingest into the Entities API. Entities created with this method are &quot;owned&quot; by the originator: other sources,
     * such as the UI, may not edit or delete these entities. The server validates entities at API call time and
     * returns an error if the entity is invalid.
     * <p>An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
     * then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
     * provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.</p>
     */
    public LatticeHttpResponse<Entity> publishEntity(RequestOptions requestOptions) {
        return publishEntity(Entity.builder().build(), requestOptions);
    }

    /**
     * Publish an entity for ingest into the Entities API. Entities created with this method are &quot;owned&quot; by the originator: other sources,
     * such as the UI, may not edit or delete these entities. The server validates entities at API call time and
     * returns an error if the entity is invalid.
     * <p>An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
     * then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
     * provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.</p>
     */
    public LatticeHttpResponse<Entity> publishEntity(Entity request) {
        return publishEntity(request, null);
    }

    /**
     * Publish an entity for ingest into the Entities API. Entities created with this method are &quot;owned&quot; by the originator: other sources,
     * such as the UI, may not edit or delete these entities. The server validates entities at API call time and
     * returns an error if the entity is invalid.
     * <p>An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
     * then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
     * provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.</p>
     */
    public LatticeHttpResponse<Entity> publishEntity(Entity request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LatticeException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Entity.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }

    public LatticeHttpResponse<Entity> getEntity(String entityId) {
        return getEntity(entityId, GetEntityRequest.builder().build());
    }

    public LatticeHttpResponse<Entity> getEntity(String entityId, RequestOptions requestOptions) {
        return getEntity(entityId, GetEntityRequest.builder().build(), requestOptions);
    }

    public LatticeHttpResponse<Entity> getEntity(String entityId, GetEntityRequest request) {
        return getEntity(entityId, request, null);
    }

    public LatticeHttpResponse<Entity> getEntity(
            String entityId, GetEntityRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities")
                .addPathSegment(entityId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Entity.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }

    /**
     * Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
     * list of fields that can be overridden. The entity in the request body should only have a value set on the field
     * specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
     * using lower_snake_case. Do not include &quot;entity&quot; in the field path.
     * <p>Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
     * concurrently for the same field path, the last writer wins.</p>
     */
    public LatticeHttpResponse<Entity> overrideEntity(String entityId, String fieldPath) {
        return overrideEntity(entityId, fieldPath, EntityOverride.builder().build());
    }

    /**
     * Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
     * list of fields that can be overridden. The entity in the request body should only have a value set on the field
     * specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
     * using lower_snake_case. Do not include &quot;entity&quot; in the field path.
     * <p>Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
     * concurrently for the same field path, the last writer wins.</p>
     */
    public LatticeHttpResponse<Entity> overrideEntity(
            String entityId, String fieldPath, RequestOptions requestOptions) {
        return overrideEntity(entityId, fieldPath, EntityOverride.builder().build(), requestOptions);
    }

    /**
     * Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
     * list of fields that can be overridden. The entity in the request body should only have a value set on the field
     * specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
     * using lower_snake_case. Do not include &quot;entity&quot; in the field path.
     * <p>Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
     * concurrently for the same field path, the last writer wins.</p>
     */
    public LatticeHttpResponse<Entity> overrideEntity(String entityId, String fieldPath, EntityOverride request) {
        return overrideEntity(entityId, fieldPath, request, null);
    }

    /**
     * Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
     * list of fields that can be overridden. The entity in the request body should only have a value set on the field
     * specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
     * using lower_snake_case. Do not include &quot;entity&quot; in the field path.
     * <p>Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
     * concurrently for the same field path, the last writer wins.</p>
     */
    public LatticeHttpResponse<Entity> overrideEntity(
            String entityId, String fieldPath, EntityOverride request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities")
                .addPathSegment(entityId)
                .addPathSegments("override")
                .addPathSegment(fieldPath)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LatticeException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Entity.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }

    /**
     * This operation clears the override value from the specified field path on the entity.
     */
    public LatticeHttpResponse<Entity> removeEntityOverride(String entityId, String fieldPath) {
        return removeEntityOverride(
                entityId, fieldPath, RemoveEntityOverrideRequest.builder().build());
    }

    /**
     * This operation clears the override value from the specified field path on the entity.
     */
    public LatticeHttpResponse<Entity> removeEntityOverride(
            String entityId, String fieldPath, RequestOptions requestOptions) {
        return removeEntityOverride(
                entityId, fieldPath, RemoveEntityOverrideRequest.builder().build(), requestOptions);
    }

    /**
     * This operation clears the override value from the specified field path on the entity.
     */
    public LatticeHttpResponse<Entity> removeEntityOverride(
            String entityId, String fieldPath, RemoveEntityOverrideRequest request) {
        return removeEntityOverride(entityId, fieldPath, request, null);
    }

    /**
     * This operation clears the override value from the specified field path on the entity.
     */
    public LatticeHttpResponse<Entity> removeEntityOverride(
            String entityId, String fieldPath, RemoveEntityOverrideRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities")
                .addPathSegment(entityId)
                .addPathSegments("override")
                .addPathSegment(fieldPath)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Entity.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }

    /**
     * This is a long polling API that will first return all pre-existing data and then return all new data as
     * it becomes available. If you want to start a new polling session then open a request with an empty
     * 'sessionToken' in the request body. The server will return a new session token in the response.
     * If you want to retrieve the next batch of results from an existing polling session then send the session
     * token you received from the server in the request body. If no new data is available then the server will
     * hold the connection open for up to 5 minutes. After the 5 minute timeout period, the server will close the
     * connection with no results and you may resume polling with the same session token. If your session falls behind
     * more than 3x the total number of entities in the environment, the server will terminate your session.
     * In this case you must start a new session by sending a request with an empty session token.
     */
    public LatticeHttpResponse<EntityEventResponse> longPollEntityEvents(EntityEventRequest request) {
        return longPollEntityEvents(request, null);
    }

    /**
     * This is a long polling API that will first return all pre-existing data and then return all new data as
     * it becomes available. If you want to start a new polling session then open a request with an empty
     * 'sessionToken' in the request body. The server will return a new session token in the response.
     * If you want to retrieve the next batch of results from an existing polling session then send the session
     * token you received from the server in the request body. If no new data is available then the server will
     * hold the connection open for up to 5 minutes. After the 5 minute timeout period, the server will close the
     * connection with no results and you may resume polling with the same session token. If your session falls behind
     * more than 3x the total number of entities in the environment, the server will terminate your session.
     * In this case you must start a new session by sending a request with an empty session token.
     */
    public LatticeHttpResponse<EntityEventResponse> longPollEntityEvents(
            EntityEventRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities/events")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LatticeException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityEventResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 408:
                        throw new RequestTimeoutError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }

    /**
     * Establishes a server-sent events (SSE) connection that streams entity data in real-time.
     * This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
     * <p>This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
     * by first streaming all pre-existing entities that match filter criteria, then continuously delivering
     * updates as entities are created, modified, or deleted.</p>
     * <p>The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
     * then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
     * indefinitely unless preExistingOnly is set to true.</p>
     * <p>Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
     * parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.</p>
     * <p>Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
     * This allows receiving only relevant data instead of complete entities.</p>
     * <p>The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
     * this provides real-time updates with minimal latency and reduced server load.</p>
     */
    public LatticeHttpResponse<Iterable<StreamEntitiesResponse>> streamEntities() {
        return streamEntities(EntityStreamRequest.builder().build());
    }

    /**
     * Establishes a server-sent events (SSE) connection that streams entity data in real-time.
     * This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
     * <p>This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
     * by first streaming all pre-existing entities that match filter criteria, then continuously delivering
     * updates as entities are created, modified, or deleted.</p>
     * <p>The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
     * then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
     * indefinitely unless preExistingOnly is set to true.</p>
     * <p>Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
     * parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.</p>
     * <p>Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
     * This allows receiving only relevant data instead of complete entities.</p>
     * <p>The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
     * this provides real-time updates with minimal latency and reduced server load.</p>
     */
    public LatticeHttpResponse<Iterable<StreamEntitiesResponse>> streamEntities(RequestOptions requestOptions) {
        return streamEntities(EntityStreamRequest.builder().build(), requestOptions);
    }

    /**
     * Establishes a server-sent events (SSE) connection that streams entity data in real-time.
     * This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
     * <p>This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
     * by first streaming all pre-existing entities that match filter criteria, then continuously delivering
     * updates as entities are created, modified, or deleted.</p>
     * <p>The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
     * then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
     * indefinitely unless preExistingOnly is set to true.</p>
     * <p>Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
     * parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.</p>
     * <p>Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
     * This allows receiving only relevant data instead of complete entities.</p>
     * <p>The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
     * this provides real-time updates with minimal latency and reduced server load.</p>
     */
    public LatticeHttpResponse<Iterable<StreamEntitiesResponse>> streamEntities(EntityStreamRequest request) {
        return streamEntities(request, null);
    }

    /**
     * Establishes a server-sent events (SSE) connection that streams entity data in real-time.
     * This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
     * <p>This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
     * by first streaming all pre-existing entities that match filter criteria, then continuously delivering
     * updates as entities are created, modified, or deleted.</p>
     * <p>The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
     * then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
     * indefinitely unless preExistingOnly is set to true.</p>
     * <p>Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
     * parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.</p>
     * <p>Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
     * This allows receiving only relevant data instead of complete entities.</p>
     * <p>The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
     * this provides real-time updates with minimal latency and reduced server load.</p>
     */
    public LatticeHttpResponse<Iterable<StreamEntitiesResponse>> streamEntities(
            EntityStreamRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/entities/stream")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new LatticeException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try {
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        Stream.fromSse(StreamEntitiesResponse.class, new ResponseBodyReader(response)), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }
}
