/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.resources.tasks.requests;

import com.anduril.core.ObjectMappers;
import com.anduril.resources.tasks.types.TaskStreamRequestTaskType;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TaskStreamRequest.Builder.class)
public final class TaskStreamRequest {
    private final Optional<Integer> heartbeatIntervalMs;

    private final Optional<Integer> rateLimit;

    private final Optional<Boolean> excludePreexistingTasks;

    private final Optional<TaskStreamRequestTaskType> taskType;

    private final Map<String, Object> additionalProperties;

    private TaskStreamRequest(
            Optional<Integer> heartbeatIntervalMs,
            Optional<Integer> rateLimit,
            Optional<Boolean> excludePreexistingTasks,
            Optional<TaskStreamRequestTaskType> taskType,
            Map<String, Object> additionalProperties) {
        this.heartbeatIntervalMs = heartbeatIntervalMs;
        this.rateLimit = rateLimit;
        this.excludePreexistingTasks = excludePreexistingTasks;
        this.taskType = taskType;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The time interval, in milliseconds, that determines the frequency at which to send heartbeat events. Defaults to 30000 (30 seconds).
     */
    @JsonProperty("heartbeatIntervalMs")
    public Optional<Integer> getHeartbeatIntervalMs() {
        return heartbeatIntervalMs;
    }

    /**
     * @return The time interval, in milliseconds, after an update for a given task before another one will be sent for the same task.
     * If set, value must be &gt;= 250.
     */
    @JsonProperty("rateLimit")
    public Optional<Integer> getRateLimit() {
        return rateLimit;
    }

    /**
     * @return Optional flag to only include tasks created or updated after the stream is initiated, and not any previous preexisting tasks.
     * If unset or false, the stream will include any new tasks and task updates, as well as all preexisting tasks.
     */
    @JsonProperty("excludePreexistingTasks")
    public Optional<Boolean> getExcludePreexistingTasks() {
        return excludePreexistingTasks;
    }

    /**
     * @return Optional filter that only returns tasks with specific types. If not provided, all task types will be streamed.
     */
    @JsonProperty("taskType")
    public Optional<TaskStreamRequestTaskType> getTaskType() {
        return taskType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TaskStreamRequest && equalTo((TaskStreamRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TaskStreamRequest other) {
        return heartbeatIntervalMs.equals(other.heartbeatIntervalMs)
                && rateLimit.equals(other.rateLimit)
                && excludePreexistingTasks.equals(other.excludePreexistingTasks)
                && taskType.equals(other.taskType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.heartbeatIntervalMs, this.rateLimit, this.excludePreexistingTasks, this.taskType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> heartbeatIntervalMs = Optional.empty();

        private Optional<Integer> rateLimit = Optional.empty();

        private Optional<Boolean> excludePreexistingTasks = Optional.empty();

        private Optional<TaskStreamRequestTaskType> taskType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TaskStreamRequest other) {
            heartbeatIntervalMs(other.getHeartbeatIntervalMs());
            rateLimit(other.getRateLimit());
            excludePreexistingTasks(other.getExcludePreexistingTasks());
            taskType(other.getTaskType());
            return this;
        }

        /**
         * <p>The time interval, in milliseconds, that determines the frequency at which to send heartbeat events. Defaults to 30000 (30 seconds).</p>
         */
        @JsonSetter(value = "heartbeatIntervalMs", nulls = Nulls.SKIP)
        public Builder heartbeatIntervalMs(Optional<Integer> heartbeatIntervalMs) {
            this.heartbeatIntervalMs = heartbeatIntervalMs;
            return this;
        }

        public Builder heartbeatIntervalMs(Integer heartbeatIntervalMs) {
            this.heartbeatIntervalMs = Optional.ofNullable(heartbeatIntervalMs);
            return this;
        }

        /**
         * <p>The time interval, in milliseconds, after an update for a given task before another one will be sent for the same task.
         * If set, value must be &gt;= 250.</p>
         */
        @JsonSetter(value = "rateLimit", nulls = Nulls.SKIP)
        public Builder rateLimit(Optional<Integer> rateLimit) {
            this.rateLimit = rateLimit;
            return this;
        }

        public Builder rateLimit(Integer rateLimit) {
            this.rateLimit = Optional.ofNullable(rateLimit);
            return this;
        }

        /**
         * <p>Optional flag to only include tasks created or updated after the stream is initiated, and not any previous preexisting tasks.
         * If unset or false, the stream will include any new tasks and task updates, as well as all preexisting tasks.</p>
         */
        @JsonSetter(value = "excludePreexistingTasks", nulls = Nulls.SKIP)
        public Builder excludePreexistingTasks(Optional<Boolean> excludePreexistingTasks) {
            this.excludePreexistingTasks = excludePreexistingTasks;
            return this;
        }

        public Builder excludePreexistingTasks(Boolean excludePreexistingTasks) {
            this.excludePreexistingTasks = Optional.ofNullable(excludePreexistingTasks);
            return this;
        }

        /**
         * <p>Optional filter that only returns tasks with specific types. If not provided, all task types will be streamed.</p>
         */
        @JsonSetter(value = "taskType", nulls = Nulls.SKIP)
        public Builder taskType(Optional<TaskStreamRequestTaskType> taskType) {
            this.taskType = taskType;
            return this;
        }

        public Builder taskType(TaskStreamRequestTaskType taskType) {
            this.taskType = Optional.ofNullable(taskType);
            return this;
        }

        public TaskStreamRequest build() {
            return new TaskStreamRequest(
                    heartbeatIntervalMs, rateLimit, excludePreexistingTasks, taskType, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
