/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeliveryConstraints.Builder.class)
public final class DeliveryConstraints {
    private final Optional<OffsetDateTime> deliverAfter;

    private final Optional<OffsetDateTime> deliverBefore;

    private final Map<String, Object> additionalProperties;

    private DeliveryConstraints(
            Optional<OffsetDateTime> deliverAfter,
            Optional<OffsetDateTime> deliverBefore,
            Map<String, Object> additionalProperties) {
        this.deliverAfter = deliverAfter;
        this.deliverBefore = deliverBefore;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Optional earliest time the task can attempt to be delivered.
     */
    @JsonProperty("deliverAfter")
    public Optional<OffsetDateTime> getDeliverAfter() {
        return deliverAfter;
    }

    /**
     * @return The latest time by which the task should be delivered.
     * If this deadline passes without successful delivery of the task, then the task will time
     * out with DELIVERY_ERROR_CODE_TIMEOUT.
     * This field is only required for tasks with retry strategies.
     */
    @JsonProperty("deliverBefore")
    public Optional<OffsetDateTime> getDeliverBefore() {
        return deliverBefore;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeliveryConstraints && equalTo((DeliveryConstraints) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeliveryConstraints other) {
        return deliverAfter.equals(other.deliverAfter) && deliverBefore.equals(other.deliverBefore);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.deliverAfter, this.deliverBefore);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<OffsetDateTime> deliverAfter = Optional.empty();

        private Optional<OffsetDateTime> deliverBefore = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeliveryConstraints other) {
            deliverAfter(other.getDeliverAfter());
            deliverBefore(other.getDeliverBefore());
            return this;
        }

        /**
         * <p>Optional earliest time the task can attempt to be delivered.</p>
         */
        @JsonSetter(value = "deliverAfter", nulls = Nulls.SKIP)
        public Builder deliverAfter(Optional<OffsetDateTime> deliverAfter) {
            this.deliverAfter = deliverAfter;
            return this;
        }

        public Builder deliverAfter(OffsetDateTime deliverAfter) {
            this.deliverAfter = Optional.ofNullable(deliverAfter);
            return this;
        }

        /**
         * <p>The latest time by which the task should be delivered.
         * If this deadline passes without successful delivery of the task, then the task will time
         * out with DELIVERY_ERROR_CODE_TIMEOUT.
         * This field is only required for tasks with retry strategies.</p>
         */
        @JsonSetter(value = "deliverBefore", nulls = Nulls.SKIP)
        public Builder deliverBefore(Optional<OffsetDateTime> deliverBefore) {
            this.deliverBefore = deliverBefore;
            return this;
        }

        public Builder deliverBefore(OffsetDateTime deliverBefore) {
            this.deliverBefore = Optional.ofNullable(deliverBefore);
            return this;
        }

        public DeliveryConstraints build() {
            return new DeliveryConstraints(deliverAfter, deliverBefore, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
