/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EntityManagerPose.Builder.class)
public final class EntityManagerPose {
    private final Optional<Position> pos;

    private final Optional<Quaternion> orientation;

    private final Map<String, Object> additionalProperties;

    private EntityManagerPose(
            Optional<Position> pos, Optional<Quaternion> orientation, Map<String, Object> additionalProperties) {
        this.pos = pos;
        this.orientation = orientation;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Geospatial location defined by this Pose.
     */
    @JsonProperty("pos")
    public Optional<Position> getPos() {
        return pos;
    }

    /**
     * @return The quaternion to transform a point in the Pose frame to the ENU frame. The Pose frame could be Body, Turret,
     * etc and is determined by the context in which this Pose is used.
     * The normal convention for defining orientation is to list the frames of transformation, for example
     * att_gimbal_to_enu is the quaternion which transforms a point in the gimbal frame to the body frame, but
     * in this case we truncate to att_enu because the Pose frame isn't defined. A potentially better name for this
     * field would have been att_pose_to_enu.
     * <p>Implementations of this quaternion should left multiply this quaternion to transform a point from the Pose frame
     * to the enu frame.</p>
     */
    @JsonProperty("orientation")
    public Optional<Quaternion> getOrientation() {
        return orientation;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntityManagerPose && equalTo((EntityManagerPose) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EntityManagerPose other) {
        return pos.equals(other.pos) && orientation.equals(other.orientation);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pos, this.orientation);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Position> pos = Optional.empty();

        private Optional<Quaternion> orientation = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EntityManagerPose other) {
            pos(other.getPos());
            orientation(other.getOrientation());
            return this;
        }

        /**
         * <p>Geospatial location defined by this Pose.</p>
         */
        @JsonSetter(value = "pos", nulls = Nulls.SKIP)
        public Builder pos(Optional<Position> pos) {
            this.pos = pos;
            return this;
        }

        public Builder pos(Position pos) {
            this.pos = Optional.ofNullable(pos);
            return this;
        }

        /**
         * <p>The quaternion to transform a point in the Pose frame to the ENU frame. The Pose frame could be Body, Turret,
         * etc and is determined by the context in which this Pose is used.
         * The normal convention for defining orientation is to list the frames of transformation, for example
         * att_gimbal_to_enu is the quaternion which transforms a point in the gimbal frame to the body frame, but
         * in this case we truncate to att_enu because the Pose frame isn't defined. A potentially better name for this
         * field would have been att_pose_to_enu.</p>
         * <p>Implementations of this quaternion should left multiply this quaternion to transform a point from the Pose frame
         * to the enu frame.</p>
         */
        @JsonSetter(value = "orientation", nulls = Nulls.SKIP)
        public Builder orientation(Optional<Quaternion> orientation) {
            this.orientation = orientation;
            return this;
        }

        public Builder orientation(Quaternion orientation) {
            this.orientation = Optional.ofNullable(orientation);
            return this;
        }

        public EntityManagerPose build() {
            return new EntityManagerPose(pos, orientation, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
