/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GeoPoint.Builder.class)
public final class GeoPoint {
    private final Optional<Position> position;

    private final Map<String, Object> additionalProperties;

    private GeoPoint(Optional<Position> position, Map<String, Object> additionalProperties) {
        this.position = position;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("position")
    public Optional<Position> getPosition() {
        return position;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GeoPoint && equalTo((GeoPoint) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GeoPoint other) {
        return position.equals(other.position);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.position);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Position> position = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GeoPoint other) {
            position(other.getPosition());
            return this;
        }

        @JsonSetter(value = "position", nulls = Nulls.SKIP)
        public Builder position(Optional<Position> position) {
            this.position = position;
            return this;
        }

        public Builder position(Position position) {
            this.position = Optional.ofNullable(position);
            return this;
        }

        public GeoPoint build() {
            return new GeoPoint(position, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
