/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PrimaryCorrelation.Builder.class)
public final class PrimaryCorrelation {
    private final Optional<List<String>> secondaryEntityIds;

    private final Map<String, Object> additionalProperties;

    private PrimaryCorrelation(Optional<List<String>> secondaryEntityIds, Map<String, Object> additionalProperties) {
        this.secondaryEntityIds = secondaryEntityIds;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The secondary entity IDs part of this correlation.
     */
    @JsonProperty("secondaryEntityIds")
    public Optional<List<String>> getSecondaryEntityIds() {
        return secondaryEntityIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PrimaryCorrelation && equalTo((PrimaryCorrelation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PrimaryCorrelation other) {
        return secondaryEntityIds.equals(other.secondaryEntityIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.secondaryEntityIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> secondaryEntityIds = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PrimaryCorrelation other) {
            secondaryEntityIds(other.getSecondaryEntityIds());
            return this;
        }

        /**
         * <p>The secondary entity IDs part of this correlation.</p>
         */
        @JsonSetter(value = "secondaryEntityIds", nulls = Nulls.SKIP)
        public Builder secondaryEntityIds(Optional<List<String>> secondaryEntityIds) {
            this.secondaryEntityIds = secondaryEntityIds;
            return this;
        }

        public Builder secondaryEntityIds(List<String> secondaryEntityIds) {
            this.secondaryEntityIds = Optional.ofNullable(secondaryEntityIds);
            return this;
        }

        public PrimaryCorrelation build() {
            return new PrimaryCorrelation(secondaryEntityIds, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
