/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Relations.Builder.class)
public final class Relations {
    private final Optional<Principal> assignee;

    private final Optional<String> parentTaskId;

    private final Map<String, Object> additionalProperties;

    private Relations(
            Optional<Principal> assignee, Optional<String> parentTaskId, Map<String, Object> additionalProperties) {
        this.assignee = assignee;
        this.parentTaskId = parentTaskId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The system, user, or team assigned to the task.
     */
    @JsonProperty("assignee")
    public Optional<Principal> getAssignee() {
        return assignee;
    }

    /**
     * @return Identifies the parent task if the task is a sub-task.
     */
    @JsonProperty("parentTaskId")
    public Optional<String> getParentTaskId() {
        return parentTaskId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Relations && equalTo((Relations) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Relations other) {
        return assignee.equals(other.assignee) && parentTaskId.equals(other.parentTaskId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.assignee, this.parentTaskId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Principal> assignee = Optional.empty();

        private Optional<String> parentTaskId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Relations other) {
            assignee(other.getAssignee());
            parentTaskId(other.getParentTaskId());
            return this;
        }

        /**
         * <p>The system, user, or team assigned to the task.</p>
         */
        @JsonSetter(value = "assignee", nulls = Nulls.SKIP)
        public Builder assignee(Optional<Principal> assignee) {
            this.assignee = assignee;
            return this;
        }

        public Builder assignee(Principal assignee) {
            this.assignee = Optional.ofNullable(assignee);
            return this;
        }

        /**
         * <p>Identifies the parent task if the task is a sub-task.</p>
         */
        @JsonSetter(value = "parentTaskId", nulls = Nulls.SKIP)
        public Builder parentTaskId(Optional<String> parentTaskId) {
            this.parentTaskId = parentTaskId;
            return this;
        }

        public Builder parentTaskId(String parentTaskId) {
            this.parentTaskId = Optional.ofNullable(parentTaskId);
            return this;
        }

        public Relations build() {
            return new Relations(assignee, parentTaskId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
