/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TaskDefinition.Builder.class)
public final class TaskDefinition {
    private final Optional<String> taskSpecificationUrl;

    private final Map<String, Object> additionalProperties;

    private TaskDefinition(Optional<String> taskSpecificationUrl, Map<String, Object> additionalProperties) {
        this.taskSpecificationUrl = taskSpecificationUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Url path must be prefixed with <code>type.googleapis.com/</code>.
     */
    @JsonProperty("taskSpecificationUrl")
    public Optional<String> getTaskSpecificationUrl() {
        return taskSpecificationUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TaskDefinition && equalTo((TaskDefinition) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TaskDefinition other) {
        return taskSpecificationUrl.equals(other.taskSpecificationUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.taskSpecificationUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> taskSpecificationUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TaskDefinition other) {
            taskSpecificationUrl(other.getTaskSpecificationUrl());
            return this;
        }

        /**
         * <p>Url path must be prefixed with <code>type.googleapis.com/</code>.</p>
         */
        @JsonSetter(value = "taskSpecificationUrl", nulls = Nulls.SKIP)
        public Builder taskSpecificationUrl(Optional<String> taskSpecificationUrl) {
            this.taskSpecificationUrl = taskSpecificationUrl;
            return this;
        }

        public Builder taskSpecificationUrl(String taskSpecificationUrl) {
            this.taskSpecificationUrl = Optional.ofNullable(taskSpecificationUrl);
            return this;
        }

        public TaskDefinition build() {
            return new TaskDefinition(taskSpecificationUrl, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
