/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TaskEventData.Builder.class)
public final class TaskEventData implements ITaskEventData {
    private final Optional<TaskEventDataTaskEvent> taskEvent;

    private final Map<String, Object> additionalProperties;

    private TaskEventData(Optional<TaskEventDataTaskEvent> taskEvent, Map<String, Object> additionalProperties) {
        this.taskEvent = taskEvent;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The task event that occurred.
     */
    @JsonProperty("taskEvent")
    public Optional<TaskEventDataTaskEvent> getTaskEvent() {
        return taskEvent;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TaskEventData && equalTo((TaskEventData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TaskEventData other) {
        return taskEvent.equals(other.taskEvent);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.taskEvent);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TaskEventDataTaskEvent> taskEvent = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TaskEventData other) {
            taskEvent(other.getTaskEvent());
            return this;
        }

        /**
         * <p>The task event that occurred.</p>
         */
        @JsonSetter(value = "taskEvent", nulls = Nulls.SKIP)
        public Builder taskEvent(Optional<TaskEventDataTaskEvent> taskEvent) {
            this.taskEvent = taskEvent;
            return this;
        }

        public Builder taskEvent(TaskEventDataTaskEvent taskEvent) {
            this.taskEvent = Optional.ofNullable(taskEvent);
            return this;
        }

        public TaskEventData build() {
            return new TaskEventData(taskEvent, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
