/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.types;

import com.anduril.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TaskEventDataTaskEvent.Builder.class)
public final class TaskEventDataTaskEvent {
    private final Optional<TaskEventDataTaskEventEventType> eventType;

    private final Optional<Task> task;

    private final Map<String, Object> additionalProperties;

    private TaskEventDataTaskEvent(
            Optional<TaskEventDataTaskEventEventType> eventType,
            Optional<Task> task,
            Map<String, Object> additionalProperties) {
        this.eventType = eventType;
        this.task = task;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The type of event that occurred for this task.
     */
    @JsonProperty("eventType")
    public Optional<TaskEventDataTaskEventEventType> getEventType() {
        return eventType;
    }

    /**
     * @return The task associated with this event.
     */
    @JsonProperty("task")
    public Optional<Task> getTask() {
        return task;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TaskEventDataTaskEvent && equalTo((TaskEventDataTaskEvent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TaskEventDataTaskEvent other) {
        return eventType.equals(other.eventType) && task.equals(other.task);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.eventType, this.task);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TaskEventDataTaskEventEventType> eventType = Optional.empty();

        private Optional<Task> task = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TaskEventDataTaskEvent other) {
            eventType(other.getEventType());
            task(other.getTask());
            return this;
        }

        /**
         * <p>The type of event that occurred for this task.</p>
         */
        @JsonSetter(value = "eventType", nulls = Nulls.SKIP)
        public Builder eventType(Optional<TaskEventDataTaskEventEventType> eventType) {
            this.eventType = eventType;
            return this;
        }

        public Builder eventType(TaskEventDataTaskEventEventType eventType) {
            this.eventType = Optional.ofNullable(eventType);
            return this;
        }

        /**
         * <p>The task associated with this event.</p>
         */
        @JsonSetter(value = "task", nulls = Nulls.SKIP)
        public Builder task(Optional<Task> task) {
            this.task = task;
            return this;
        }

        public Builder task(Task task) {
            this.task = Optional.ofNullable(task);
            return this;
        }

        public TaskEventDataTaskEvent build() {
            return new TaskEventDataTaskEvent(eventType, task, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
