/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.anduril.resources.oauth2;

import com.anduril.core.ClientOptions;
import com.anduril.core.LatticeApiException;
import com.anduril.core.LatticeException;
import com.anduril.core.LatticeHttpResponse;
import com.anduril.core.ObjectMappers;
import com.anduril.core.RequestOptions;
import com.anduril.errors.BadRequestError;
import com.anduril.errors.UnauthorizedError;
import com.anduril.resources.oauth2.requests.GetTokenRequest;
import com.anduril.resources.oauth2.types.GetTokenResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.FormBody;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawOAuth2Client {
    protected final ClientOptions clientOptions;

    public RawOAuth2Client(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Exchange authorization code, refresh token, client credentials, or resource owner credentials for an access token
     */
    public LatticeHttpResponse<GetTokenResponse> getToken(GetTokenRequest request) {
        return getToken(request, null);
    }

    /**
     * Exchange authorization code, refresh token, client credentials, or resource owner credentials for an access token
     */
    public LatticeHttpResponse<GetTokenResponse> getToken(GetTokenRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/v1/oauth/token");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        FormBody.Builder body = new FormBody.Builder();
        try {
            body.add("grant_type", String.valueOf(request.getGrantType()));
            if (request.getCode().isPresent()) {
                body.add("code", String.valueOf(request.getCode().get()));
            }
            if (request.getRedirectUri().isPresent()) {
                body.add("redirect_uri", String.valueOf(request.getRedirectUri().get()));
            }
            if (request.getClientId().isPresent()) {
                body.add("client_id", String.valueOf(request.getClientId().get()));
            }
            if (request.getClientSecret().isPresent()) {
                body.add(
                        "client_secret",
                        String.valueOf(request.getClientSecret().get()));
            }
            if (request.getRefreshToken().isPresent()) {
                body.add(
                        "refresh_token",
                        String.valueOf(request.getRefreshToken().get()));
            }
            if (request.getUsername().isPresent()) {
                body.add("username", String.valueOf(request.getUsername().get()));
            }
            if (request.getPassword().isPresent()) {
                body.add("password", String.valueOf(request.getPassword().get()));
            }
            if (request.getScope().isPresent()) {
                body.add("scope", String.valueOf(request.getScope().get()));
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body.build())
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/x-www-form-urlencoded")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new LatticeHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetTokenResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new LatticeApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new LatticeException("Network error executing HTTP request", e);
        }
    }
}
